use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanResult {
    pub session_id: String,
    pub completed_phases: Vec<String>,
    pub complexity_level: Option<u8>,
    pub plan_complete: bool,
    pub phases_remaining: Vec<String>,
    pub executable_plan: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct PhaseRecord {
    phase: String,
    data: serde_json::Value,
    confidence: f64,
}

#[derive(Debug, Clone, Default)]
struct PlanningSession {
    phases: HashMap<String, PhaseRecord>,
    complexity_level: Option<u8>,
}

#[derive(Debug, Clone, Default)]
pub struct PlanningEngine {
    sessions: HashMap<String, PlanningSession>,
}

impl PlanningEngine {
    pub fn plan_search(
        &mut self,
        query: &str,
        complexity: &str,
        time_sensitivity: &str,
        confidence: f64,
    ) -> PlanResult {
        let level = match complexity {
            "simple" => 1,
            "moderate" => 2,
            "complex" => 3,
            _ if is_simple_query(query) => 1,
            _ => 2,
        };
        let session_id = self
            .plan_intent(
                "",
                query,
                infer_query_type(query),
                time_sensitivity,
                confidence,
            )
            .session_id;
        self.plan_complexity(
            &session_id,
            level,
            if level == 1 { 1 } else { 3 },
            if level == 1 { 1 } else { 4 },
            "generated by aggregate plan_search",
            confidence,
        );
        self.plan_sub_query(
            &session_id,
            "sq1",
            query,
            "answer with verifiable sources",
            "excludes unrelated background unless needed to verify the answer",
            confidence,
        );
        self.plan_search_term(&session_id, query, "sq1", 1, "targeted", confidence);
        self.plan_tool_mapping(
            &session_id,
            "sq1",
            "web_search",
            "primary query requires current sourced web evidence",
            confidence,
        );
        self.plan_execution(&session_id, vec![vec!["sq1".into()]], vec![], 1, confidence)
    }

    pub fn plan_intent(
        &mut self,
        session_id: &str,
        core_question: &str,
        query_type: &str,
        time_sensitivity: &str,
        confidence: f64,
    ) -> PlanResult {
        let session_id = self.session_id(session_id);
        self.record(
            &session_id,
            "intent_analysis",
            serde_json::json!({
                "core_question": core_question,
                "query_type": query_type,
                "time_sensitivity": time_sensitivity
            }),
            confidence,
        );
        self.result(&session_id)
    }

    pub fn plan_complexity(
        &mut self,
        session_id: &str,
        level: u8,
        estimated_sub_queries: u32,
        estimated_tool_calls: u32,
        justification: &str,
        confidence: f64,
    ) -> PlanResult {
        self.record(
            session_id,
            "complexity_assessment",
            serde_json::json!({
                "level": level,
                "estimated_sub_queries": estimated_sub_queries,
                "estimated_tool_calls": estimated_tool_calls,
                "justification": justification
            }),
            confidence,
        );
        if let Some(session) = self.sessions.get_mut(session_id) {
            session.complexity_level = Some(level.clamp(1, 3));
        }
        self.result(session_id)
    }

    pub fn plan_sub_query(
        &mut self,
        session_id: &str,
        id: &str,
        goal: &str,
        expected_output: &str,
        boundary: &str,
        confidence: f64,
    ) -> PlanResult {
        self.append(
            session_id,
            "query_decomposition",
            serde_json::json!({
                "id": id,
                "goal": goal,
                "expected_output": expected_output,
                "boundary": boundary
            }),
            confidence,
        );
        self.result(session_id)
    }

    pub fn plan_search_term(
        &mut self,
        session_id: &str,
        term: &str,
        purpose: &str,
        round: u32,
        approach: &str,
        confidence: f64,
    ) -> PlanResult {
        self.append(
            session_id,
            "search_strategy",
            serde_json::json!({
                "term": term,
                "purpose": purpose,
                "round": round,
                "approach": approach
            }),
            confidence,
        );
        self.result(session_id)
    }

    pub fn plan_tool_mapping(
        &mut self,
        session_id: &str,
        sub_query_id: &str,
        tool: &str,
        reason: &str,
        confidence: f64,
    ) -> PlanResult {
        self.append(
            session_id,
            "tool_selection",
            serde_json::json!({
                "sub_query_id": sub_query_id,
                "tool": tool,
                "reason": reason
            }),
            confidence,
        );
        self.result(session_id)
    }

    pub fn plan_execution(
        &mut self,
        session_id: &str,
        parallel: Vec<Vec<String>>,
        sequential: Vec<String>,
        estimated_rounds: u32,
        confidence: f64,
    ) -> PlanResult {
        self.record(
            session_id,
            "execution_order",
            serde_json::json!({
                "parallel": parallel,
                "sequential": sequential,
                "estimated_rounds": estimated_rounds
            }),
            confidence,
        );
        self.result(session_id)
    }

    fn session_id(&mut self, session_id: &str) -> String {
        let session_id = if session_id.is_empty() {
            Uuid::new_v4().simple().to_string()[..12].to_string()
        } else {
            session_id.to_string()
        };
        self.sessions.entry(session_id.clone()).or_default();
        session_id
    }

    fn record(&mut self, session_id: &str, phase: &str, data: serde_json::Value, confidence: f64) {
        let session_id = self.session_id(session_id);
        let session = self.sessions.entry(session_id).or_default();
        session.phases.insert(
            phase.to_string(),
            PhaseRecord {
                phase: phase.to_string(),
                data,
                confidence,
            },
        );
    }

    fn append(&mut self, session_id: &str, phase: &str, item: serde_json::Value, confidence: f64) {
        let session_id = self.session_id(session_id);
        let session = self.sessions.entry(session_id).or_default();
        let existing = session
            .phases
            .entry(phase.to_string())
            .or_insert_with(|| PhaseRecord {
                phase: phase.to_string(),
                data: serde_json::json!([]),
                confidence,
            });
        if let Some(items) = existing.data.as_array_mut() {
            items.push(item);
        }
        existing.confidence = confidence;
    }

    fn result(&self, session_id: &str) -> PlanResult {
        let Some(session) = self.sessions.get(session_id) else {
            return PlanResult {
                session_id: session_id.to_string(),
                completed_phases: Vec::new(),
                complexity_level: None,
                plan_complete: false,
                phases_remaining: vec!["intent_analysis".into()],
                executable_plan: None,
            };
        };

        let mut completed = phase_names()
            .into_iter()
            .filter(|phase| session.phases.contains_key(*phase))
            .map(str::to_string)
            .collect::<Vec<_>>();
        completed.sort();
        let required = required_phases(session.complexity_level.unwrap_or(3));
        let phases_remaining = required
            .iter()
            .filter(|phase| !session.phases.contains_key(**phase))
            .map(|phase| (*phase).to_string())
            .collect::<Vec<_>>();
        let plan_complete = phases_remaining.is_empty();
        let executable_plan = if plan_complete {
            let mut map = serde_json::Map::new();
            for (phase, record) in &session.phases {
                map.insert(phase.clone(), record.data.clone());
            }
            Some(serde_json::Value::Object(map))
        } else {
            None
        };

        PlanResult {
            session_id: session_id.to_string(),
            completed_phases: completed,
            complexity_level: session.complexity_level,
            plan_complete,
            phases_remaining,
            executable_plan,
        }
    }
}

fn infer_query_type(query: &str) -> &'static str {
    if query.contains(" vs ") || query.contains("对比") || query.contains("比较") {
        "comparative"
    } else if query.contains("为什么") || query.contains("原因") {
        "analytical"
    } else {
        "factual"
    }
}

fn is_simple_query(query: &str) -> bool {
    query.chars().count() < 80
}

fn phase_names() -> Vec<&'static str> {
    vec![
        "intent_analysis",
        "complexity_assessment",
        "query_decomposition",
        "search_strategy",
        "tool_selection",
        "execution_order",
    ]
}

fn required_phases(level: u8) -> Vec<&'static str> {
    match level {
        1 => vec![
            "intent_analysis",
            "complexity_assessment",
            "query_decomposition",
        ],
        2 => vec![
            "intent_analysis",
            "complexity_assessment",
            "query_decomposition",
            "search_strategy",
            "tool_selection",
        ],
        _ => phase_names(),
    }
}
